#!/bin/bash

sudo apt-get update
sudo apt-get install -y git curl wget htop zip unzip screen neofetch virt-what
sudo cp ~/dotfiles/bin/exa-linux-x86_64 /usr/local/bin/exa

echo '
source ~/dotfiles/.exports' >> ~/.profile

echo '
source ~/dotfiles/.aliases' >> ~/.bashrc

echo '
source ~/dotfiles/.functions' >> ~/.bashrc

source ~/dotfiles/.profile
source ~/dotfiles/.aliases
source ~/dotfiles/.functions
